# Generated by Django 3.2.3 on 2021-06-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddressPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('subnet', models.GenericIPAddressField()),
                ('mask', models.PositiveSmallIntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('cluster', models.BooleanField(default=False)),
                ('edc_id', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('ip_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.ipaddresspool')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.product')),
            ],
        ),
    ]
