# Generated by Django 3.0.5 on 2020-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cluster',
            field=models.BooleanField(default=False),
        ),
    ]
