# Generated by Django 3.0.5 on 2020-05-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ip_address', models.GenericIPAddressField()),
                ('dev1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev1', to='devices.Device')),
                ('dev2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev2', to='devices.Device')),
            ],
        ),
    ]
