# Generated by Django 3.0.5 on 2020-05-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='edc_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
