# Generated by Django 3.0.5 on 2020-06-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.IpAddressPool'),
        ),
    ]
