# Generated by Django 3.0.5 on 2020-06-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_ip_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='data_center',
        ),
        migrations.DeleteModel(
            name='DataCenter',
        ),
    ]
